const HINDI_LABELS = {
  'My Purchase Requests': 'मेरी खरीद अनुरोध',
  'All purchase requests across the organisation': 'संगठन भर के सभी खरीद अनुरोध',
  'Your submitted purchase requests and their status': 'आपके सबमिट किए गए खरीद अनुरोध और उनकी स्थिति',
  'New Purchase Request': 'नई खरीद अनुरोध',
  'Purchase Request Number': 'खरीद अनुरोध संख्या',
  'Requester Name / On Whose Behalf': 'अनुरोधकर्ता का नाम / किसकी ओर से',
  'Status': 'स्थिति',
  'Priority': 'प्राथमिकता',
  'Department': 'विभाग',
  'Requested By': 'अनुरोधकर्ता',
  'Request Date': 'अनुरोध तिथि',
  'Required By': 'आवश्यक तिथि',
  'Actions': 'कार्यवाही',
  'No purchase requests found.': 'कोई खरीद अनुरोध नहीं मिला।',
  'Create Your First Request': 'अपना पहला अनुरोध बनाएं',
  'Select Department': 'विभाग चुनें',
  'Required By Date': 'आवश्यक तिथि',
  'Date of Request': 'अनुरोध की तिथि',
  'Auto-filled': 'स्वतः भरा गया',
  'Pending Approval': 'अनुमोदन लंबित',
  'Approved': 'स्वीकृत',
  'Partially Approved': 'आंशिक स्वीकृत',
  'Rejected': 'अस्वीकृत',
  'Low': 'कम',
  'Medium': 'मध्यम',
  'High': 'उच्च',
  'Urgent': 'अत्यावश्यक',
};

export default HINDI_LABELS;