/**
 * Picklist Header Meta — ERPNext-style two-column display of picklist metadata.
 */
export default function PicklistHeaderMeta({ picklist }) {
  if (!picklist) return null;

  const fmt = (d) => {
    if (!d) return '—';
    const p = d.split('-');
    if (p.length === 3 && p[0].length === 4) return `${p[2]}/${p[1]}/${p[0]}`;
    return d;
  };

  const leftFields = [
    { label: 'Company', value: picklist.company || 'K95 Foods Private Limited' },
    { label: 'Purpose', value: picklist.purpose || 'Delivery' },
    { label: 'Customer Name', value: picklist.customer_name || '—' },
    { label: 'Sales Order', value: picklist.so_number || '—' },
  ];

  const rightFields = [
    { label: 'Warehouse', value: picklist.warehouse || 'Finished Goods - KFPL' },
    { label: 'Transporter', value: picklist.transporter || '—' },
    { label: 'Packaging Type', value: picklist.packaging_type || '—' },
    { label: 'Purchase Order No.', value: picklist.po_number || picklist.so_number || '—' },
    { label: 'Dispatch Date', value: fmt(picklist.dispatch_date) },
  ];

  return (
    <div className="bg-white border border-slate-200 rounded-xl p-4">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-2">
        {/* Left column */}
        <div className="space-y-2">
          {leftFields.map(f => (
            <div key={f.label} className="flex items-baseline gap-2">
              <span className="text-xs font-semibold text-slate-500 w-32 shrink-0 text-right">{f.label}:</span>
              <span className="text-sm text-slate-900">{f.value}</span>
            </div>
          ))}
        </div>
        {/* Right column */}
        <div className="space-y-2">
          {rightFields.map(f => (
            <div key={f.label} className="flex items-baseline gap-2">
              <span className="text-xs font-semibold text-slate-500 w-36 shrink-0 text-right">{f.label}:</span>
              <span className="text-sm text-slate-900">{f.value}</span>
            </div>
          ))}
        </div>
      </div>
      {/* Additional meta */}
      <div className="mt-3 pt-3 border-t border-slate-100 grid grid-cols-2 md:grid-cols-4 gap-3 text-xs">
        {picklist.generated_by && (
          <div>
            <span className="text-slate-500">Generated By:</span>
            <p className="font-medium text-slate-700 mt-0.5">{picklist.generated_by}</p>
          </div>
        )}
        {picklist.completed_by && (
          <div>
            <span className="text-slate-500">Completed By:</span>
            <p className="font-medium text-slate-700 mt-0.5">{picklist.completed_by}</p>
          </div>
        )}
        {picklist.appointment_date && (
          <div>
            <span className="text-slate-500">Appointment Date:</span>
            <p className="font-medium text-slate-700 mt-0.5">{fmt(picklist.appointment_date)}</p>
          </div>
        )}
        {picklist.expiry_date && (
          <div>
            <span className="text-slate-500">Expiry Date:</span>
            <p className="font-medium text-slate-700 mt-0.5">{fmt(picklist.expiry_date)}</p>
          </div>
        )}
      </div>
    </div>
  );
}